### ISSUE TITLE
`Search` query not working 

### ISSUE THREAD

**Issue by happylolonly** [octokit/plugin-paginate-graphql.js#162]
### What happened?

Hi, I am using your plugin, but such request not working...
Example same request is working.
https://docs.github.com/en/graphql/overview/explorer

```
const data = await octokit.graphql.paginate(
    `query paginate($cursor: String) {
      search(query: "test", type: ISSUE, first: 1, after: $cursor) {
        pageInfo {
          hasNextPage
          endCursor
        },
        nodes {
          ... on Issue {
            title,
            url,
          }
        }
      }
   }`
```

### Versions

last

### Relevant log output

```shell
{
  search: { pageInfo: { hasNextPage: false, endCursor: null }, nodes: [] }
}
```
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by happylolonly** [comment]
Seems issue not with your repo, will provide more info little bit later.

**Comment by happylolonly** [comment]
Was need to add `is:issue` to search query, don't understand why, if we specify `type: ISSUE`
Not very clear for devs. Debugged much time.

**Comment by kfcampbell** [comment]
Thanks for following up! That's certainly an obnoxious problem to have to deal with. Hopefully the explanation you provided here can save somebody else time in the future.
