### ISSUE TITLE
Possible broken test since the cursor reference is misnamed.

### ISSUE THREAD

**Issue by bensquire** [octokit/plugin-paginate-graphql.js#17]
https://github.com/octokit/plugin-paginate-graphql.js/blob/cb6dca4e0c5d9a6661bdbda040ce6cfd0cbe2a37/test/paginate.test.ts#L109

`$curosr` rather than `$cursor`

**Comment by wolfy1339** [comment]
Thanks for the report! Would you be willing to send in a Pull Request to fix this issue

**Comment by wolfy1339** [comment]
This was fixed in #167
