### ISSUE TITLE
[BUG]: v5.0 is failing with "SyntaxError: … does not provide an export named 'paginateGraphQL'"

### ISSUE THREAD

**Issue by awendt** [octokit/plugin-paginate-graphql.js#180]
### What happened?

Trying to use the package as documented:

```bash
$ npm install @octokit/core @octokit/plugin-paginate-graphql --save

added 11 packages, and audited 12 packages in 3s

found 0 vulnerabilities
```

My `package.json` for a minimal example:

```json
{
  "name": "plugin-paginate-graphql",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "type": "module",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@octokit/core": "^6.0.1",
    "@octokit/plugin-paginate-graphql": "^5.0.0"
  }
}
```

```javascript
// test-plugin.js
import { Octokit } from "@octokit/core";
import { paginateGraphQL } from "@octokit/plugin-paginate-graphql";
```

Then:

```bash
$ node test-plugin.js
import { paginateGraphQL } from "@octokit/plugin-paginate-graphql";
         ^^^^^^^^^^^^^^^
SyntaxError: The requested module '@octokit/plugin-paginate-graphql' does not provide an export named 'paginateGraphQL'
```

Am I missing something?

### Versions

- Node.js v20.5.1
- `@octokit/core` v6.0.1
- `@octokit/plugin-paginate-graphql` v5.0.0

### Relevant log output

```shell
$ node test-plugin.js
file:///Users/andrewendt/tmp/plugin-paginate-graphql/test-plugin.js:2
import { paginateGraphQL } from "@octokit/plugin-paginate-graphql";
         ^^^^^^^^^^^^^^^
SyntaxError: The requested module '@octokit/plugin-paginate-graphql' does not provide an export named 'paginateGraphQL'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:122:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:188:5)
    at async DefaultModuleLoader.import (node:internal/modules/esm/loader:228:24)
    at async loadESM (node:internal/process/esm_loader:40:7)
    at async handleMainPromise (node:internal/modules/run_main:66:12)

Node.js v20.5.1
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wolfy1339** [comment]
This is very annoying... This isn't the first time this issue has been brought up with Octokit packages.

It's something to do with the `exports` map in the `package.json`, we haven't quite nailed down the proper format quite yet

Can you try changing it so that the exports map looks like so:
```json
"exports": {
    "types": "dist-types/index.d.ts",
    "import": "dist-bundle/index.js"
}
```

**Comment by awendt** [comment]
@wolfy1339 There is no `dist-bundle` folder:

```
$ tree node_modules/@octokit/plugin-paginate-graphql/
node_modules/@octokit/plugin-paginate-graphql/
├── LICENSE
├── README.md
├── dist-node
│   ├── index.js
│   └── index.js.map
├── dist-src
│   ├── errors.js
│   ├── extract-page-info.js
│   ├── index.js
│   ├── iterator.js
│   ├── merge-responses.js
│   ├── object-helpers.js
│   ├── page-info.js
│   └── paginate.js
├── dist-types
│   ├── errors.d.ts
│   ├── extract-page-info.d.ts
│   ├── index.d.ts
│   ├── iterator.d.ts
│   ├── merge-responses.d.ts
│   ├── object-helpers.d.ts
│   ├── page-info.d.ts
│   └── paginate.d.ts
├── dist-web
│   ├── index.js
│   └── index.js.map
└── package.json
```

That's why changing the `exports` as you suggested leads to:

```
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/path/to/plugin-paginate-graphql/node_modules/@octokit/plugin-paginate-graphql/dist-bundle/index.js' imported from /path/to/plugin-paginate-graphql/test-plugin.js
```

**Comment by kachick** [comment]
Is this a different issue of #177?

The PR for it https://github.com/octokit/plugin-paginate-graphql.js/pull/178 is not yet released to npm https://www.npmjs.com/package/@octokit/plugin-paginate-graphql?activeTab=versions

**Comment by awendt** [comment]
> Is this a different issue of #177?
> 
> The PR for it #178 is not yet released to npm https://www.npmjs.com/package/@octokit/plugin-paginate-graphql?activeTab=versions

Good point! Is there any way for me to test that change without a release?

**Comment by kachick** [comment]
Now I'm just waiting for the official release.  
But when I tried to solve this, [build and adjust structure for dist-*](https://github.com/kachick/plugin-paginate-graphql.js/pull/2/commits) and [pointing with git path from dependent repository](
https://github.com/kachick/wait-other-jobs/pull/723/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R29).

Below is my struggle log...

<img width="823" alt="screen_shot 2024-03-13 19 54 50" src="https://github.com/octokit/plugin-paginate-graphql.js/assets/1180335/e69d5a69-fab7-4100-8084-a463ec21ed70">

**Comment by wolfy1339** [comment]
The release workflow is currently failing, it will get fixed by https://github.com/octokit/plugin-paginate-graphql.js/pull/181
